#+title: About
#+author: Preston Pan
#+description: About me and my contact information
#+language: en
#+OPTIONS: broken-links:t
#+date: <2023-06-26 Mon>

* About Me
** whoami?
Preston Pan. Although, that is not really important for the enjoyment of ret2pop, and
it is certainly not the focus at all. Ret2pop is a separate entity, controlled only
by the will of Francois. Ret2pop is a relentlessly curious force willing to entertain
ideas that are unconventional and unorthodox; Preston Pan is the individual that tries
to live this out and fails in a somewhat cringy manner.

Some might know me as ret2pop, some as Preston Pan, and others as LiCoO2. Others may know that
I have an ENS domain, at ~ret2pop.eth~.
** Contact
Here are all the methods you should use to contact me:
*** Professional
Here you can find [[file:resume.pdf][my resume]] in both pdf and [[file:resume.org][html]] which contains it all. I am always open for new job opportunities!
*** IRC
- ret2pop on nullring.xyz, 6697. Go to #nullring; this channel is the most active, probably.
*** Matrix
contact me on matrix at ~@ret2pop:matrix.nullring.xyz~.
*** Email
- ret2pop@gmail.com
- ret2pop@nullring.xyz
*** Amateur Radio (In case the world ends)
My callsign is ~VE7PPN~.
*** Linkedin
You can see my [[https://ca.linkedin.com/in/preston-pan-4aa635296][personal linkedin profile]].
*** How Old am I?
born in 12/23/2005, but does it really matter?
** Keys
This is for all my public keys that are important. Note: for cryptocurrency public keys, see
[[file:index.org][the index]] page with all my addresses. Use either your own self hosted scanner, or another
public scanner to get my public keys.
- This is [[file:public-key.asc][my gpg public key for ret2pop]].
- This is [[file:id_ed25519.pub][my ssh key]].
