#+title: ret2pop
#+author: Preston Pan
#+date: <2023-06-11 Sun>
#+description: My website for all things.
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />

* What is this?
It's ret2pop! My website for all things math. Wait, no. Computer science.
Music. Okay, let me try that again. Is this even a website?

It's ret2pop, a wholistic experience powered by NixOS and Emacs.
** so how did you actually do that?
By using the ~org-publish~ function, ~org-roam~, and ~org-journal~,
as well as writing a lot of things with a literate config. To see more, see my
[[file:config/emacs.org][emacs configuration]] and my [[file:config/nix.org][NixOS configuration]].
** So, where is this website of yours located?
https://ret2pop.nullring.xyz, it is the road to enlightenment.
* Wait, so where are your dotfiles?
To use my dotfiles, download the ISO image for the installer, log in, and run:
#+begin_src bash
  SYSTEM=continuity DRIVE=sda-simple nix_installer
#+end_src
then reboot, and run:
#+begin_src bash
  cd $HOME/monorepo && git pull
#+end_src
** Post-setup
In emacs, run ~M-x all-the-icons-install-fonts, ~~M-x nerd-icons-install-fonts~, and ~M-x org-roam-db-sync~. Install your music to ~$HOME/music~ for
emms.
* License
See the [[file:LICENSE.org][license]]. The style.css has its own license.
