#+title: ret2pop
#+author: Preston Pan
#+date: <2023-06-11 Sun>
#+description: My website for all things.
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />

* What is this?
It's ret2pop! My website for all things math. Wait, no. Computer science.
Music. Okay, let me try that again. Is this even a website?

It's ret2pop, a wholistic experience powered by NixOS and Emacs.
** so how did you actually do that?
By using the ~org-publish~ function, ~org-roam~, and ~org-journal~,
as well as writing a lot of things with a literate config. To see more, see my
[[file:config/emacs.org][emacs configuration]] and my [[file:config/nix.org][NixOS configuration]].
** So, where is this website of yours located?
https://ret2pop.net, it is the road to enlightenment.
* Wait, so where are your dotfiles?
To use my dotfiles, download the [[file:nix-installer.iso][ISO image]] for the installer. Note that you can validate the ISO image with the [[file:nix-installer.iso.sha256][checksum file]] provided:
#+begin_src bash
  sha256sum -c nix-installer.iso.sha256
#+end_src
with the ISO in the same directory. This install installs a certain commit hash of my monorepo. Flash the image, log into the installer, and run:
#+begin_src bash
  nix_installer
#+end_src
then reboot, and run:
#+begin_src bash
  cd $HOME/monorepo && git pull
#+end_src
That's all! Note that if you install with an encrypted disk, you will have to run:
#+begin_src bash
  echo "password123" > /tmp/secret.key
#+end_src
before ~nix_installer~.
** Post-setup
In emacs, run ~M-x all-the-icons-install-fonts, ~~M-x nerd-icons-install-fonts~, and ~M-x org-roam-db-sync~. Install your music to ~$HOME/music~ for
emms. In firefox, go to the three-bar menu and enable all the add-ons that were automatically installed. Set up the ~mu~ program in order to
send and receive email, along with modifying the corresponding mbsync and msmtp commands. Change ~nix/flakevars.nix~ to your liking.
* License
See the [[file:LICENSE][license]] The style.css has its own license.
