:PROPERTIES:
:ID:       122fd244-ffeb-47d0-89ce-bf9bc6f01b70
:END:
#+title: limit
#+author: Preston Pan
#+description: Pushing math to its limit
#+LATEX_HEADER: \usepackage{tikz-cd}

#+options: broken-links:t

* Introduction
A limit in mathematics is a tool used to describe the intuitive process
of a value or a set of values tending towards another. First, we will define
limits as they pertain to sequences, and then we will define them on [[id:b1f9aa55-5f1e-4865-8118-43e5e5dc7752][functions]].
For a sequence $\{s_{n}\}$:

\begin{align*}
\lim s_{n} = s \iff \forall \epsilon > 0, \exists N , n > N \implies | s_{n} - s | < \epsilon
\end{align*}

What this means is that at some point in the sequence, for some choice of epsilon, no matter how small
it is, there has to be an index where every term after that index is closer to $s$ than epsilon. If
some single number $s$ and sequence $\{s_{n}\}$ fulfills this criteria, then it is said that the limit
of the sequence is $s$. Generally speaking, we use the set $\mathbb{R} \cup \{ -\infty, +\infty \}$, where there is a natural
ordering:

\begin{align*}
\forall a \in \mathbb{R}, - \infty < a < +\infty
\end{align*}
defined. Note that we can define equivalence relations on these symbols, but algebra reamins undefined.
** Unbounded Sequences
Unbounded sequences can still limit to $+\infty$ or $-\infty$, although the limit does not exist
for many unbounded sequences. If a sequence is one of:
1. unbounded above
2. unbounded below
but not both, it is possible that such sequences limit to $\infty$.
** Limits on Monotone Sequences
An increasing sequence is a sequence $\{s_{n}\}$ defined such that:
\begin{align*}
\forall n \in \mathbb{N}, \forall m \in \mathbb{N}, n \ge m \implies s_{n} \ge s_{m}.
\end{align*}

#+begin_theorem
The limit of monotone sequences always exists.
#+end_theorem

#+begin_proof
We know:
\begin{align*}
\lim s_{n} = s \iff \forall \epsilon > 0, \exists N, n > N \implies | s_{n} - s | < \epsilon \\
\end{align*}
which is equivalent to:
\begin{align*}
\lim s_{n} = s \iff \forall \epsilon > 0, \exists N, n > N \implies s - \epsilon < s_{n} < s + \epsilon
\end{align*}
and our sequence $\{s_{n}\}$ is monotone. If $\{s_{n}\}$ is increasing, we have:
\begin{align*}
s_{n + 1} \ge s_{n}
\end{align*}
for all n. Without loss of generality we shall assume $\{s_{n}\}$ is increasing. Then we take two cases:
1. $\{s_{n}\}$ is bounded.
2. $\{s_{n}\}$ is unbounded.
In the case $\{s_{n}\}$ is bounded:
\begin{align}
\label{}
\exists M, \forall n, s_{n} \le M \\
s_{0} \le ... \le s_{n} \le s_{n + 1} \le s_{n + 2} \le ... \le M
\end{align}

#+end_proof
** Limits as Objects
Limits can also be objects. This is most aptly demonstrated in more abstract fields of mathematics such as algebraic topology,
where the central "object of importance" (a common theme in math is one where you have an object of importance) is the net.
Specifically, the limits of universal nets have a deep relation to compactness, but here we will explore the most informative and essential
form of this idea and its algebraic properties. We will quickly go over the one-point compactification, and then introduce the stone-cech
compactification after.
** One Point Compactification
:PROPERTIES:
:ID:       339b32e7-ad89-40d7-8b11-5b293bd1056f
:END:
The one-point compactification is the simplest possible compactification of a topological space as you are adding only one point, and it does have a
rather simple definition, although it is really only interesting in locally compact hausdorff spaces.

Let $X$ be a locally compact Hausdorff space, then its one-point compactification is $X \cup \lbrace \infty \rbrace$, where the topology defined on
this is as follows:
1. if $U$ is open in $X$, $U$ is open in $X \cup \lbrace \infty \rbrace$.
2. if $F \subset X$ is a compact subset and $\infty \in F^{c}$, then $F^{c}$ is open.
The topology generated by these open sets it the topology associated with the one-point compactification of $X$. If $X$ is locally compact hausdorff,
then in fact this topology is compact hausdorff, which is why it is the notable case. We shall see this in a proof.
#+begin_theorem
If $X$ is a locally compact Hausdorff space and $X^{\plus} = X \cup \lbrace \infty \rbrace$ is the one-point compactification of $X$, then $X^{\plus}$ is a
compact Hausdorff space.
#+end_theorem

#+begin_proof
In order to prove this, we must first prove it is compact, then we must prove it is Hausdorff. For the first we will use proof by
contradiction. Let $\lbrace x_{\alpha}\rbrace$ be a universal net in
$X^{\plus}$, then suppose $\lbrace  x_{\alpha}\rbrace$ does not converge in $X^{\plus}$. Then $\lbrace x_{\alpha} \rbrace$ also doesn't converge to $\infty$, and let $U_{\infty}$ be an open
neighborhood of $\infty$ which $\lbrace x_{\alpha} \rbrace$ is not eventually in. Then the complement $U_{\infty}^{c}$ must be compact (the only way to define a
neighborhood of $\infty$ is in terms of the complements of compact sets). But if $\lbrace x_{\alpha} \rbrace$ is eventually in $U_{\infty}^{c}$ it is eventually in a compact
set and must converge. However $\lbrace x_{\alpha} \rbrace$ is universal and therefore must eventually be in either $U_{\infty}$ (impossible by construction) or $U_{\infty}^{c}$
(also impossible). Contradiction!

To prove that it is Hausdorff, it is enough to prove that $\infty$ is separated from the other points (this is because all points in $X$ already are
separated by open sets in $X$). Let $x \in X$, then there exists an open neighborhood $U$ such that $\infty \not \in \overline{U}$ (choose $U$ such that
$\overline{U}$ is compact, and this set exists due to locally compact property of $X$). Then $\overline{U}^{c}$ is a neighborhood of $\infty$ and is disjoint from $U$.
#+end_proof

Importantly, the one-point compactification can be thought of as a generalisation of the compactification of $\mathbb{R}^n$ via identification with
$S^n$, and it can be thought of as undoing stereographic projection. It is also the smallest possible compactification as you are only adding one
point. Note that it is possible for $X$ itself to be compact, and in that case $\infty$ is a disconnected component.
** Stone-Cech Compactification
:PROPERTIES:
:ID:       14bebb09-2e38-4b55-adc0-97ba571331af
:END:
We can construct the Stone Cech Compcatification on a completely regular topological space $X$, which will require a specific construction
but will at least give us the Hausdorff property in the compactified space. To start, let $A$ be the set of all $f_{\alpha}: X \rightarrow [0, 1]_{\alpha}$  such that $f$ is
continuous (with $\alpha$ being an arbitrary but consistent index), and let us define a Tychonoff space $Y = \prod_{\alpha \in A}[0, 1]_{\alpha}$  and an embedding $\phi: X \rightarrow Y$
where the embedding $\phi$ is defined as $(\phi(x))_{\alpha }= f_{\alpha}(x)$. Then the idea is that the /closure/ of $\phi(X)$ in $Y$ is a compactification of $X$.
In fact, this is sort of analogous to currying in the theory of computer science, or delayed or /lazy evaluation/, and as we shall see, it will share
similar algebraic properties.

How do we know the space is compact? We know that $Y$ is compact because $[0, 1]$ is compact, and we apply Tychonoff's theorem. How do we know that
$\overline{\phi(X)}$ is compact? It is closed and a subset of a compact set. However, what we have /not/ shown thus far is that $\phi(X)$ is truly an embedding. To see
this, the completely regular property of $X$ saves the day; if we /didn't/ have this property, then it would be possible for some two points to /never/ be
separated by any function, and then you'd lose the one-to-one property of $\phi$. Also, $\phi$ is clearly always continuous; we use the property that
$\pi_{\alpha}\circ \phi(x) = f_{\alpha}(x)$, and $\phi$ is continuous iff its projections $f_{\alpha}$ are continuous. Now all we need to show is that $\phi^{-1}$ is continuous, which we can
also do with the completely regular property.

Before this we will introduce some more standard notation that will make it seem much more like currying in programming. For example we can just drop
the index $\alpha$ and index by the function $f$ instead. Of course in real programming this is terrible as you'd want to index by pointer, however in math
we have infinite power so we're just going to index by the literal function. How this will work is that instead of writing
$(\phi(x))_{\alpha} = f_{\alpha}(x)$, we will instead
write $\phi(x)(f) = f(x)$, and we will index our space with the set $A$ directly. The standard way to write the space $\overline{\phi(X)}$ is actually $\beta X$ so we'll
write it that way from now on as well. I just thought that the above would have been a more intuitive explanation for the concept for me in the past. We will
call $\phi$ the /evaluation map/, for obvious reasons if you come from programming.
#+begin_theorem
if $X$ is a completely regular space and $\phi: X \rightarrow \beta X$ is the evaluation map of all continuous $f: X \rightarrow [0, 1]$, then $\phi$ is an open map on its image $\phi(X)$.
#+end_theorem

#+begin_proof
In this proof we will use the net definition of continuity. Suppose $\phi(x_{\alpha}) \rightarrow \phi(x)$, yet $x_{\alpha} \not \rightarrow x$. Then there exists some open neighborhood  $U$ of
$x$ such that $x_{\alpha}$ is not eventually in $U$. Because of complete regularity, there exists a map $f$ separating $x$ from $U^{c}$. If
$\phi(x_{\alpha}) \rightarrow \phi(x)$, then $\pi_{f} \circ \phi(x_{\alpha}) \rightarrow \pi_{f} \circ \phi(x)$, but clearly this is equivalent to $f(x_{\alpha}) \rightarrow f(x)$. Any subnet of a convergent net converges to the same
value, so we create a subnet $\lbrace y_{\alpha}\rbrace$ of $\lbrace x_{\alpha} \rbrace$ such that $\lbrace y_{\alpha}\rbrace$ is eventually in
$U^{c}$ (this is possible because $\lbrace x_{\alpha}\rbrace$ is frequently in $U^{c}$). Then $f(y_{\alpha}) \rightarrow 1$ ($f(U^{c}) \equiv 1$ by construction), yet $f(x) = 0$. But this is clearly absurd, because $\lbrace y_{\alpha} \rbrace$
converges uniquely, and the constant $1$ net cannot converge to $0$! Contradiction.
#+end_proof
*** Algebra on Limits
Often times it is useful to think of limits as /objects in themselves/ rather than an object that you apply to, say, a sequence. Often times algebras on
different /kinds/ of limits enables oneself to draw on connections between limits and many other fields of mathematics. For instance, the /closure/ of a
set is exactly the same set with all its limit points included, and both closures, and as we will see, limits, are /idempotent/, which is to say,
applying them once is the same thing as applying them twice. Note that if $f: X \rightarrow Y$ where $Y$ is any topological space and $f$ is any continuous
function, then $\beta f(X) = f(\beta X)$, which one can represent with a commutative diagram, where $\beta f$ is the /unique extension/ of the mapping $f$. Actually, in a moment
we will see that the functor commuting is equivalent to the /limit/ commuting on nets.

*** The Universal Property
We say the following diagram commutes:

