:PROPERTIES:
:ID:       122fd244-ffeb-47d0-89ce-bf9bc6f01b70
:END:
#+title: limit
#+author: Preston Pan
#+description: Pushing math to its limit

#+options: broken-links:t

* Introduction
A limit in mathematics is a tool used to describe the intuitive process
of a value or a set of values tending towards another. First, we will define
limits as they pertain to sequences, and then we will define them on [[id:b1f9aa55-5f1e-4865-8118-43e5e5dc7752][functions]].
For a sequence $\{s_{n}\}$:

\begin{align*}
\lim s_{n} = s \iff \forall \epsilon > 0, \exists N , n > N \implies | s_{n} - s | < \epsilon
\end{align*}

What this means is that at some point in the sequence, for some choice of epsilon, no matter how small
it is, there has to be an index where every term after that index is closer to $s$ than epsilon. If
some single number $s$ and sequence $\{s_{n}\}$ fulfills this criteria, then it is said that the limit
of the sequence is $s$. Generally speaking, we use the set $\mathbb{R} \cup \{ -\infty, +\infty \}$, where there is a natural
ordering:

\begin{align*}
\forall a \in \mathbb{R}, - \infty < a < +\infty
\end{align*}
defined. Note that we can define equivalence relations on these symbols, but algebra reamins undefined.
** Unbounded Sequences
Unbounded sequences can still limit to $+\infty$ or $-\infty$, although the limit does not exist
for many unbounded sequences. If a sequence is one of:
1. unbounded above
2. unbounded below
but not both, it is possible that such sequences limit to $\infty$.
** Limits on Monotone Sequences
An increasing sequence is a sequence $\{s_{n}\}$ defined such that:
\begin{align*}
\forall n \in \mathbb{N}, \forall m \in \mathbb{N}, n \ge m \implies s_{n} \ge s_{m}.
\end{align*}

#+begin_theorem
The limit of monotone sequences always exists.
#+end_theorem

#+begin_proof
We know:
\begin{align*}
\lim s_{n} = s \iff \forall \epsilon > 0, \exists N, n > N \implies | s_{n} - s | < \epsilon \\
\end{align*}
which is equivalent to:
\begin{align*}
\lim s_{n} = s \iff \forall \epsilon > 0, \exists N, n > N \implies s - \epsilon < s_{n} < s + \epsilon
\end{align*}
and our sequence $\{s_{n}\}$ is monotone. If $\{s_{n}\}$ is increasing, we have:
\begin{align*}
s_{n + 1} \ge s_{n}
\end{align*}
for all n. Without loss of generality we shall assume $\{s_{n}\}$ is increasing. Then we take two cases:
1. $\{s_{n}\}$ is bounded.
2. $\{s_{n}\}$ is unbounded.
In the case $\{s_{n}\}$ is bounded:
\begin{align}
\label{}
\exists M, \forall n, s_{n} \le M \\
s_{0} \le ... \le s_{n} \le s_{n + 1} \le s_{n + 2} \le ... \le M
\end{align}

#+end_proof
** Limits as Objects
Limits can also be objects. This is most aptly demonstrated in more abstract fields of mathematics such as algebraic topology,
where the central "object of importance" (a common theme in math is one where you have an object of importance) is the net.
Specifically, the limits of universal nets have a deep relation to compactness, but here we will explore the most informative and essential
form of this idea and its algebraic properties. We will quickly go over the one-point compactification, and then introduce the stone-cech
compactification after.
*** One Point Compactification
:PROPERTIES:
:ID:       339b32e7-ad89-40d7-8b11-5b293bd1056f
:END:
*** Stone Cech Compcatification
:PROPERTIES:
:ID:       14bebb09-2e38-4b55-adc0-97ba571331af
:END:
We can construct the Stone Cech Compcatification on a completely regular topological space $X$, which will require a specific construction
but will at least give us the Hausdorff property in the compactified space. To start, let $A$ be the set of all $f_{\alpha}: X \rightarrow [0, 1]_{\alpha}$  such that $f$ is
continuous (with $\alpha$ being an arbitrary but consistent index), and let us define a Tychonoff space $Y = \prod_{\alpha \in A}[0, 1]_{\alpha}$  and an embedding $\phi: X \rightarrow Y$
where the embedding $\phi$ is defined as $(\phi(x))_{\alpha }= f_{\alpha}(x)$. Then the idea is that the /closure/ of $\phi(X)$ in $Y$ is a compactification of $X$.
In fact, this is sort of analogous to currying in the theory of computer science.

How do we know the space is compact? We know that $Y$ is compact because $[0, 1]$ is compact, and we apply Tychonoff's theorem. How do we know that
$\overline{\phi(X)}$ is compact? It is closed and a subset of a compact set. However, what we have /not/ shown thus far is that $\phi(X)$ is truly an embedding. To see
this, the completely regular property of $X$ saves the day; if we /didn't/ have this property, then it would be possible for some two points to /never/ be
separated by any function, and then you'd lose the one-to-one property of $\phi$.
\begin{align}
\lim x_{\alpha}
\end{align}
