#+title: Interesting RSS Feeds
#+author: Preston Pan
#+date: <2023-06-09 Fri>
#+description: My list of blogs, news sites, and channels.
#+html_head: <link rel="stylesheet" type="text/css" href="../style.css" />

* Feed :elfeed:
This is the feed I use for Elfeed, and the elfeed-org package allows me to publish
them here in an automated fashion. This is why Emacs is so great!
** News :news:
These are the news articles that I subscribe to. Some of these are politics related
but I mostly just want to inform myself about technology subjects.
*** [[https://news.ycombinator.com/rss][Hacker News]]
Hacker News!
*** [[https://www.propublica.org/feeds/propublica/main][Propublica]]
Free news! 
*** [[https://api.quantamagazine.org/feed/][Quanta Magazine]]
Credibility: misreported on ER EPR correspondence
** Podcasts :podcast:
*** [[https://notrelated.xyz/rss][Not Related]] :lukesmith:
This is a podcast by Luke Smith that talks about anything that he wants to.
** Forums :forum:
*** [[http://lesserwrong.com/feed.xml][LessWrong]]
The birthplace of bay area rationalism.
*** [[https://list.nullring.xyz/discussion/new.atom][Nullring Discussion]]
My own mailing list feed.
** Science Journals :journal:
I like to get new information about recent studies related to technology.
*** [[http://www.nature.com/nmat/current_issue/rss/][Nature]]
Nature is a prestigious journal with a good bit of good content.
*** NASA :nasa:
This is a list of NASA feeds:
**** [[https://www.nasa.gov/technology/feed/][NASA Tech]]
**** [[https://www.nasa.gov/aeronautics/feed/][NASA Aeronautics]]
**** [[https://www.nasa.gov/missions/station/feed/][NASA Station]]
**** [[https://www.nasa.gov/missions/artemis/feed/][NASA Artemis]]
** YouTube :youtube:
These are YouTube channels that I find interesting enough to keep up with. Note that I keep
up with a variety of thinkers that I may or may not disagree with, but they are nonetheless
the most intellectual version of what their general cohort say:
*** [[https://youtube.com/feeds/videos.xml?channel_id=UCFQMnBA3CS502aghlcr0_aw][CoffeeZilla]]
Exposes scams.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UC28n0tlcNSa1iPe5mettocg][VoidZilla]]
Extras from coffezilla channel.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UCKGCof63C6pLCFT4R6YPEtQ][Jred]]
This youtube channel is about existential dread apparently. I don't have such a thing but it's fun to watch anyways.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UC1qIX2Ya5ErOrU9tv0GVUAw][CyberYamu]]
A channel about the daily experience of a schizotypal girl.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UCwVevVbti5Uuxj6Mkl5NHRA][Lemonade Stand]]
Podcast channel that talks about modern day economics.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA][Lex Fridman]]
He has some good guests on sometimes.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UCXl4i9dYBrFOabk0xGmbkRA][Dwarkesh Patel]]
Makes podcasts whose guests are usually AI researchers of some kind.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC1yNl2E66ZzKApQdRuTQ4tw][Sabine Hossenfelder]]
Youtube channel about mostly physics related content (I do not endorse her views on string theory).
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g][PBS Space Time]]
PBS space time is a channel that discusses various (sometimes cutting edge) topics in Physics in an expert manner.
I find that they are highly accurate, and the host is highly educated in Physics.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCWvq4kcdNI1r1jZKFw9TiUA][ScienceClic]]
ScienceClic is another YouTube channel that does an especially good job at covering cutting edge ideas in physics.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCMxiv15iK_MFayY_3fU9loQ][UnHerd]] :podcast:
UnHerd is one of the best, most interesting political podcasts, period, in my opinion. Though, do note that learning
about politics is kind of pointless.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC8oZG4c6FzOX4pbdpZBeCPw][Huey Li]]
He's a comedian and kind of a China hater.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC554eY5jNUfDq3yDOJYirOQ][Destiny]]
He debates people on various issues.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw][3blue1brown]]
Makes really good educational videos. I hope to make videos like this one day.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCGSGPehp0RWfca-kENgBJ9Q][Jreg]]
Makes good videos about basically anything.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA][Luke Smith]]
Makes good videos about Linux and life stuff.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCSNBahoyPlMUz-3U2e_Czcw][Bridges]] :podcast:
This podcast is run by Destiny, and it features good guests.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UCgv4dPk_qZNAbUW9WkuLPSA][Atrioc]]
Features some good marketing and economics content. Big A is his secondary channel.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCdBXOyqr8cDshsp7kcKDAkg][Big A]]
Marketing Monday features good economics content.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCTpmmkp1E4nmZqWPS-dl5bg][Quanta Magazine]]
See above.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC5PPbhNfajmhPq7RvkMgVmw][Ceadda of Mercia]]
Videos about NRx.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA][Mental Outlaw]]
Linux videos.
*** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCU1oodg2ptN51N5rwevwnng][Unlearning Economics]]
Videos about economics from a Marxist perspective.
*** [[https://youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA][Veritasium]]
Makes good educational videos.
** Blogs :blog:
Here are some interesting blogs, many of which are from substack.
*** [[https://ollama.com/blog/rss.xml][Ollama]]
For new updates to new LLM models that I can pull with ollama.
*** [[https://terrytao.wordpress.com/feed/][Terence Tao]]
I like math.
*** [[https://lukesmith.xyz/index.xml][Luke Smith]] :lukesmith:
Luke Smith is quite the interesting person.
*** Substack :substack:
These are a list of all the substack blogs that exist.
**** [[https://graymirror.substack.com/feed][Gray Mirror]]
Curtis Yarvin is quite the interesting person.
**** [[https://www.richardhanania.com/feed][Richard Hanania]]
Richard is a political commentator.
**** [[https://paulkrugman.substack.com/feed][Paul Krugman]]
He makes good economics blogs as he used to be a professional economist.
**** [[https://www.overcomingbias.com/feed][Overcoming Bias]]
Makes the case for the glorious reign of Futarchy!! (Not what you think it is).
**** [[https://betonit.ai/feed][Bryan Caplan]]
Anarcho Capitalist person.
