#+title: Reconstructing Postmodernism
#+author: Preston Pan
#+description: 
#+html_head: <link rel="stylesheet" type="text/css" href="../style.css" />
#+html_head: <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
#+html_head: <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
#+html_head: <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
#+html_head: <link rel="manifest" href="/site.webmanifest">
#+html_head: <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
#+html_head: <meta name="msapplication-TileColor" content="#da532c">
#+html_head: <meta name="theme-color" content="#ffffff">
#+html_head: <meta name="viewport" content="width=1000; user-scalable=0;" />
#+language: en
#+OPTIONS: broken-links:t

* Introduction
In the collective subconscious there is this idea of the "norm" -- a
set of expected cultural attitudes and beliefs that other people hold
in any given society. This idea is used to analyze hierarchical
structures found in society, manifest in concepts like the patriarchy,
queer rights, black liberation, and others. There are many frameworks
that include all of the above as subframeworks and synthesize them in
some way, but often they have a couple ideas in common: that the
concepts that implicitly infect our society in some way via some
hierarchical order are often unjustified and could be dissolved
without much loss. I propose the following: that the conclusions
presented (that often social hierarchies are unjustified) are true
/in some sense/, but that the real story is more complicated. I posit
that our inability to solve the problem of society and our treatment
of minorities isn't a /problem of society/, but rather a framing problem.

* The Bleak Culture
Our current society is broken. This is a view shared by a vast
majority of people, but many people hold this exact view for a
multitude of reasons. I hold this view because I believe that no
current cultural narrative solves the problem of our "current
generation". The progressive narrative posits that our problems in
society are highly linked with our inability to cope with social
inequalities, often treating minorities and, often times, regular
people poorly in favor of those with high status. The conservative
answer to culture is that we must turn back, back to something that
has been shown to work in the past.

