#+title: Representative Voting
#+author: Preston Pan
#+date: [2024-01-01]
#+subtitle: By {{{author}}}, 2024

#+description: What do we do about voter turnout? Voting demographics? Polarization?

#+language: en
#+OPTIONS: broken-links:t
* Introduction
Current voting systems are broken, and people argue about ways to solve it. Many talk about about ranked-choice
voting or other ballot-systems, but I argue that the real problem in voting has to do with game theory principles.
In this article I endorse a system that has been tried out before, but has been forgotten: /random representation/. I
argue that it has game theoretic foundations that make it superior to other kinds of voting systems.

** The Model
Let us assume there is a small probability of swinging the
election $$ \rho $$, and a large reward for winning the election $$ W $$.
Let us assume that there are two candidates, and the probability of
voting for a single candidate is 50%. Therefore, the final probability
distribution for the number of votes each candidate gets is binomial,
centered around the mean outcome (which is the outcome where there are
an equal amount of votes on each side, and we can count the number of
/red/ votes only; let's let $$ k $$ represent the number of red votes).
Let's remind ourselves of the binomial distribution:
\begin{align}
  P(X = k) = { n \choose k } p^{k}(1 - p)^{n - k}
\end{align}
where $$ n $$ is the number of samples, and $$ k $$ is the observed
number. Now, we can calculate the probability
